name: Node gendiff

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache: 'npm'
      - run: make install
      - run: make lint
      - run: make test-coverage

      - name: SonarCloud Scan
        uses: 'SonarSource/sonarcloud-github-action@e3531b7d5f71e6659c0784be199e89d130ec7737'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
